# Generated by Django 4.2.4 on 2023-08-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
