# Generated by Django 4.2.4 on 2023-08-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_alter_assessment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresult',
            name='submission_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
