# Generated by Django 4.2.4 on 2023-08-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_alter_assessmentresult_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
