# Generated by Django 4.2.4 on 2023-08-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_alter_assessment_date_created_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.UniqueConstraint(fields=('candidate', 'assessment'), name='unique_assessment'),
        ),
    ]
