# Generated by Django 4.2.4 on 2023-08-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_assessmentresult_unique_assessment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assessmentresult',
            name='unique_assessment',
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.UniqueConstraint(fields=('candidate', 'assessment'), name='unique_assessment_result'),
        ),
    ]
