# Generated by Django 4.2.4 on 2023-08-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_remove_question_assessment'),
        ('assessment', '0008_assessmentresult_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(related_name='assessments', to='question.question'),
        ),
    ]
