# Generated by Django 4.2.4 on 2023-08-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_alter_answer_selected_choice_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
