# Generated by Django 4.2.4 on 2023-08-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_choice_unique_choice'),
        ('assessment', '0013_alter_assessment_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='assessments', to='question.question'),
        ),
    ]
