# Generated by Django 4.2.4 on 2023-08-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_choice_question_alter_question_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='assessment',
        ),
    ]
