# Generated by Django 4.2.4 on 2023-08-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.PositiveIntegerField()),
                ('assessment_id', models.PositiveIntegerField()),
                ('question_id', models.PositiveIntegerField()),
                ('question_type', models.CharField(max_length=3)),
                ('selected_choice_id', models.PositiveIntegerField(null=True)),
                ('code', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
