# Generated by Django 4.2.4 on 2023-08-04 18:05

import candidate.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_candidate_email_alter_candidate_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='candidate',
            managers=[
                ('objects', candidate.manager.CandidateManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='username',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
